type = "javascript"
account_id = "f1c2ab938f91fa76af879185e872f215"

[site]
bucket = "dist"
entry-point = "workers"

[env.dev]
name = "holo-dev"
route = "holo-dev.poi.cat/*"
zone_id = "4f27c98d90fd913efe41acfb093e019a"

[env.prod]
name = "holo"
route = "holo.poi.cat/*"
zone_id = "4f27c98d90fd913efe41acfb093e019a"
